const payments = [
    {
        method: 'WechatPay',
        region: 'China',
        systemMethod: 'WECHATPAY',
        quickPay: true,
        web: true,
        mobileWeb: false,
        transactionQR: true,
    },
    {
        method: 'WechatPay',
        region: 'Malaysia',
        systemMethod: 'WECHATPAY',
        quickPay: true,
        web: true,
        mobileWeb: false,
        transactionQR: true,
    },
    {
        method: 'Presto',
        region: 'Malaysia',
        systemMethod: 'PRESTO',
        quickPay: true,
        web: true,
        mobileWeb: true,
        transactionQR: true,
    },
    {
        method: 'Alipay',
        region: 'China',
        systemMethod: 'ALIPAY',
        quickPay: true,
        web: true,
        mobileWeb: true,
        transactionQR: true,
    },
    {
        method: 'TNG',
        region: 'Malaysia',
        systemMethod: 'TNG',
        quickPay: true,
        web: true,
        mobileWeb: true,
    },
    {
        method: 'Boost',
        region: 'Malaysia',
        systemMethod: 'BOOST',
        quickPay: true,
        web: true,
        mobileWeb: true,
        transactionQR: true,
    },
    {
        method: 'Maybank',
        region: 'Malaysia',
        systemMethod: 'MAYBANK',
        quickPay: true,
        web: true,
    },
    {
        method: 'GrabPay',
        region: 'Malaysia',
        systemMethod: 'GRABPAY',
        quickPay: true,
        web: true,
        mobileWeb: true,
    },
    {
        method: 'ShopeePay',
        region: 'Malaysia',
        systemMethod: 'SHOPEEPAY',
        quickPay: true,
        web: true,
        mobileWeb: true,
    },
    {
        method: 'Gobiz',
        region: 'Malaysia',
        systemMethod: 'GOBIZ',
        web: true,
        mobileWeb: true,
    },
    {
        method: 'Paydee',
        region: 'Malaysia',
        systemMethod: 'PAYDEE',
        web: true,
        mobileWeb: true,
    },
    {
        method: 'Zapp',
        region: 'Malaysia',
        systemMethod: 'ZAPP',
        quickPay: true,
        mobileWeb: true,
    },
    {
        method: 'Tapay',
        region: 'Malaysia',
        systemMethod: 'TAPAY',
        quickPay: true,
    },
    {
        method: 'MCash',
        region: 'Malaysia',
        systemMethod: 'MCASH',
        quickPay: true,
        web: true,
        mobileWeb: true,
    },
    {
        method: 'Lazada',
        region: 'Malaysia',
        systemMethod: 'LAZADA',
        quickPay: true,
    },
    {
        method: 'FPX',
        region: 'Malaysia',
        systemMethod: 'FPX',
        web: true,
        mobileWeb: true,
    },
    {
        method: 'SarawakPay',
        region: 'Malaysia',
        systemMethod: 'SARAWAKPAY',
        quickPay: true,
        web: true,
        mobileWeb: true,
    },
    {
        method: 'FavePay',
        region: 'Malaysia',
        systemMethod: 'FAVEPAY',
        quickPay: true,
        web: true,
    },
    {
        method: 'BInfinite',
        region: 'Malaysia',
        systemMethod: 'BINFINITE',
        quickPay: true,
        web: true,
    },
    {
        method: 'Alipay+',
        region: 'Malaysia',
        systemMethod: 'ALIPAYPLUS',
        quickPay: true,
        web: true,
        mobileWeb: true,
    },
    {
        method: 'SenHengPay',
        region: 'Malaysia',
        systemMethod: 'SENHENGPAY',
        web: true,
        mobileWeb: true,
    },
    {
        method: 'Split',
        region: 'Malaysia',
        systemMethod: 'SPLIT',
        web: true,
    },
    {
        method: 'IOUPay',
        region: 'Malaysia',
        systemMethod: 'IOUPAY',
        web: true,
    },
    {
        method: 'Atome',
        region: 'Malaysia',
        systemMethod: 'ATOME',
        quickPay: true,
        web: true,
    },
    {
        method: 'NetsPay',
        region: 'Singapore',
        systemMethod: 'NETSPAY',
        web: true,
        retailQR: true,
    },
    {
        method: 'Setel',
        region: 'Malaysia',
        systemMethod: 'SETEL',
        quickPay: true,
        web: true,
    },
];

export default payments;