export type ErrorEntry = {
  description: string;
  solution?: string;
};

/**
 * Combined lookup map for all Revenue Monster error codes.
 * Sources: OAuth error codes + API error codes doc.
 */
export const ERROR_CODES: Record<string, ErrorEntry> = {
  // ── OAuth / Grant errors ─────────────────────────────────────────────
  InvalidRequest: {
    description: "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.",
    solution: "Refer to request parameter(s) as described in the API documentation and retry.",
  },
  InvalidGrant: {
    description: "Invalid grant.",
    solution: "Check redirect URI — it must exactly match the request URI query string.",
  },
  InvalidClient: {
    description: "Invalid client.",
    solution: "Client is not registered. Try again with the correct clientId and clientSecret.",
  },
  InvalidCode: {
    description: "Invalid authorization code.",
    solution: "This is not a valid authorization code. Request a new authorization code.",
  },
  InActiveClient: {
    description: "Client mode is inactive.",
    solution: "This client/application is disabled. Log in to Merchant Portal and reactivate it.",
  },
  InvalidScope: {
    description: "The requested scope is invalid, unknown, or malformed.",
    solution: "Check scope — supported values: manage_payment, manage_store, get_merchant_profile, get_user_profile. Requested scope cannot exceed the user scope.",
  },
  UnAuthorizedClient: {
    description: "The client is not authorized to request this method.",
    solution: "Use a different client to request this method.",
  },
  UnSupportedGrantType: {
    description: "Unsupported grant type.",
    solution: "Supported grant types: Client Credentials, Authorization Code, Refresh Token.",
  },
  UnSupportedResponseType: {
    description: "The authorization server does not support obtaining an authorization code using this method.",
    solution: "Use responseType=code in the request URI query string and try again.",
  },
  AccessDenied: {
    description: "The resource owner or authorization server denied the request.",
    solution: "User is inactivated in the system. Please try again.",
  },
  InternalError: {
    description: "The authorization server encountered an unexpected condition.",
    solution: "If this persists, contact customer support.",
  },
  TemporaryUnAvailable: {
    description: "The authorization server is currently unable to handle the request due to temporary overloading or maintenance.",
    solution: "If this persists, contact customer support.",
  },

  // ── API error codes ──────────────────────────────────────────────────
  ALIPAY_CHINA_NOT_ACTIVE: { description: "Alipay China is not active.", solution: "Contact Revenue Monster to activate (016-6999168 / support@revenuemonster.my)." },
  ACCESS_TOKEN_READ_FAIL: { description: "Cannot read access token file." },
  ACCOUNT_FROZEN: { description: "Your account has been frozen.", solution: "Contact support." },
  ACCOUNT_INACTIVE: { description: "User account is inactive." },
  ACCOUNT_NOT_FOUND: { description: "Account does not exist." },
  ACCOUNT_SUSPENDED: { description: "This account is temporarily locked." },
  AGREEMENT_ALREADY_SIGNED: { description: "Agreement already signed." },
  AGREEMENT_NOT_FOUND: { description: "Agreement not found." },
  AGREMENT_NOT_SIGNED: { description: "Agreement not signed." },
  ACCESS_TOKEN_FAIL: { description: "Failed to request access token." },
  ALIPAY_CLIENT_DUPLICATE: { description: "Alipay client duplicate." },
  ALREADY_MASTER_MERCHANT: { description: "Already master merchant." },
  API_ENDPOINT_NOT_FOUND: { description: "The API endpoint does not exist." },
  API_INACTIVE: { description: "This API version is no longer active.", solution: "Please migrate to API v3." },
  AUTH_CODE_EXPIRED: { description: "Customer code expired.", solution: "Please scan again." },
  AUTH_CODE_INVALID: { description: "Customer code invalid.", solution: "Please scan again." },
  AUTH_CODE_MIS_MATCH: { description: "Invalid customer code." },
  AUTH_CODE_USED: { description: "Customer code has already been used.", solution: "Please refresh for another transaction." },
  AUTHORIZATION_HEADER_NOT_ALLOWED: { description: "Authorization header is not allowed." },
  BANK_ERROR: { description: "Bank system error." },
  BOOST_MALAYSIA_NOT_ACTIVE: { description: "Boost Malaysia is not active.", solution: "Contact Revenue Monster to activate merchant for Boost." },
  BUSINESS_CATEGORY_NOT_FOUND: { description: "Business category not found." },
  BUYER_ACCOUNT_ERROR: { description: "Customer account error." },
  BUYER_ACCOUNT_IN_ACTIVE: { description: "Customer account is inactive." },
  CAMPAIGN_NOT_FOUND: { description: "Campaign not found." },
  CANNOT_UPDATE_SAME_PHONE_NUMBER: { description: "Cannot update the same phone number." },
  CHOP_STAMP_NOT_ACTIVE: { description: "Chop stamp not active." },
  CHOP_STAMP_NOT_FOUND: { description: "Chop stamp not found." },
  CHOP_STAMP_QUANTITY_EXCEED: { description: "Exceeded the number of chop stamp cards." },
  CLIENT_INVALID: { description: "Invalid client." },
  CLIENT_NO_PERMISSION: { description: "Developer application does not have permission to access." },
  CLIENT_NOT_AUTHORIZE_STORE: { description: "Merchant does not have authorization to enter this store." },
  CLIENT_NOT_FOUND: { description: "Developer application client not found." },
  CLIENT_NOT_SET_PUBLIC_KEY: { description: "Developer application does not set public key." },
  CLIENT_PRODUCT_NOT_SETUP: { description: "Developer application product not set up." },
  CLIENT_PRODUCT_SUBSCRIBED: { description: "Developer application already subscribed to product." },
  COMPANY_TYPE_NOT_FOUND: { description: "Company type not found." },
  CUSTOMER_REACHED_TRANSACTION_LIMIT: { description: "Customer has reached their transaction limit." },
  DAILY_PAYMENT_EXCEEDED: { description: "Daily payment limit exceeded." },
  DEFAULT_STORE_DELETE_NOT_ALLOWED: { description: "Default store is not allowed to be deleted." },
  DOES_NOT_ALLOW_MULTIPLE_BATCH_PROCESSING: { description: "Multiple batch processing is not allowed." },
  DOES_NOT_HAVE_ACTIVE_WALLET: { description: "Does not have active wallet.", solution: "Contact Revenue Monster to activate wallet." },
  EMAIL_DUPLICATE: { description: "Email address already exists." },
  EMAIL_NOT_FOUND: { description: "Email address not found." },
  EXCEEDED_LIMIT: { description: "Rate limit exceeded." },
  EXCEED_TIME_FOR_REVERSE_TRANSACTION: { description: "Exceeded time for reversal of transaction." },
  EXPIRY_INVALID: { description: "Invalid expiry type." },
  EXPIRY_MIN: { description: "Minimum expiry day." },
  FAILED_TO_REVERSE_ORDER: { description: "Failed to reverse order." },
  FILE_NOT_FOUND: { description: "File not found." },
  GENERIC_TEMPLATE_INVALID: { description: "Invalid generic template." },
  GRABPAY_MALAYSIA_MERCHANT_ID_NOT_SET: { description: "GrabPay Malaysia is not active.", solution: "Contact Revenue Monster to activate merchant for GrabPay." },
  GRABPAY_MALAYSIA_NOT_ACTIVE: { description: "GrabPay Malaysia is not active.", solution: "Contact Revenue Monster to activate merchant for GrabPay." },
  GRANT_TYPE_INVALID: { description: "Invalid grant type." },
  INSUFFICIENT_CARD_BALANCE: { description: "Insufficient customer balance." },
  INSUFFICIENT_LOYALTY_BALANCE: { description: "Insufficient loyalty balance." },
  INSUFFICIENT_MERCHANT_BALANCE: { description: "Insufficient merchant balance." },
  INSUFFICIENT_PERMISSION_LEVEL: { description: "Insufficient permission." },
  INSUFFICIENT_REFUND_AMOUNT: { description: "Insufficient refund amount." },
  INTERNAL_ERROR: { description: "Internal error.", solution: "If this persists, contact customer support." },
  INVALID_AGREEMENT_VERSION: { description: "Invalid agreement version." },
  INVALID_APP_ID: { description: "Invalid parameters." },
  INVALID_CHARSET: { description: "Invalid charset." },
  INVALID_CLIENT: { description: "Invalid client." },
  INVALID_ENCRYPTION: { description: "Invalid encryption." },
  INVALID_FILE: { description: "Invalid file." },
  INVALID_FORMAT: { description: "Invalid format." },
  INVALID_HTTP_METHOD: { description: "Invalid HTTP method." },
  INVALID_ID: { description: "Invalid ID." },
  INVALID_IMAGE_DIMENSION: { description: "Invalid image dimension." },
  INVALID_LOYALTY_CREDIT_CODE: { description: "Invalid loyalty credit code." },
  INVALID_OTP_CODE: { description: "Invalid OTP code." },
  INVALID_PARAMETER: { description: "Invalid parameters." },
  INVALID_PARAMETER_ID: { description: "Invalid parameter ID." },
  INVALID_PAYMENT_SUBSCRIPTION_METHOD: { description: "Invalid payment subscription method." },
  INVALID_PRIVATE_KEY: { description: "Invalid private key.", solution: "Ensure your private key is correctly formatted and matches the public key registered on the Merchant Portal." },
  INVALID_PUBLIC_KEY: { description: "Invalid public key." },
  INVALID_REQUEST: { description: "The request is missing a required parameter, includes an invalid parameter value, or is otherwise malformed.", solution: "Refer to request parameters as described in the API documentation and retry." },
  INVALID_REQUEST_SIGNATURE: { description: "The request signature is invalid.", solution: "Verify your private key, signature generation logic, and that the request body is correctly sorted before signing." },
  INVALID_SCOPE: { description: "Invalid scope." },
  INVALID_SIGNATURE: { description: "Invalid signature.", solution: "Check your signing logic — ensure the plaintext is constructed correctly with sorted body, method, nonceStr, requestUrl, signType, and timestamp." },
  INVALID_TERMINAL_TOKEN: { description: "Invalid terminal token.", solution: "Contact Revenue Monster support." },
  INVALID_TIMESTAMP: { description: "Could not authenticate — timestamp mismatch.", solution: "Ensure X-Timestamp is within an acceptable time window of the server time." },
  KEYWORD_DUPLICATE: { description: "Duplicate keyword." },
  KEYWORD_KEY_INVALID: { description: "Invalid keyword key." },
  KEYWORD_NOT_FOUND: { description: "Keyword not found." },
  LIST_TEMPLATE_INVALID: { description: "Invalid list template." },
  LOYALTY_BATCH_ALREADY_GENERATE_CSV: { description: "CSV for loyalty batch has already been generated." },
  LOYALTY_BATCH_ALREADY_ZIP: { description: "Loyalty batch has already been zipped." },
  LOYALTY_BIRTHDAY_FIELD_NOT_REQUIRED: { description: "Birth date field not required." },
  LOYALTY_CREDIT_NOT_ENABLED: { description: "Loyalty credit not enabled." },
  LOYALTY_EXPIRED: { description: "Loyalty point expired." },
  LOYALTY_GENERATE_ERROR: { description: "Error in generating loyalty point." },
  LOYALTY_INSUFFICIENT: { description: "Insufficient loyalty points." },
  LOYALTY_MEMBER_REGISTRATION_TOO_MANY: { description: "Creating too many members.", solution: "Limit is 1,000 members per request." },
  LOYALTY_NOT_CORRECT_FORMAT: { description: "Loyalty not correct format." },
  LOYALTY_NOT_FOUND: { description: "Loyalty not found." },
  LOYALTY_NOT_SUBSCRIBED: { description: "Not subscribed to loyalty program." },
  LOYALTY_POINT_ALREADY_REDEEMED: { description: "Loyalty point already redeemed." },
  LOYALTY_POINT_IS_PROCESSING: { description: "Loyalty point is processing." },
  LOYALTY_POINT_MISSING: { description: "Loyalty point missing for certain custom ID." },
  LOYALTY_QUANTITY_MAX: { description: "Member has exceeded the maximum quantity of loyalty points." },
  LOYALTY_SPENDING_NOT_ALLOWED: { description: "Loyalty spending not allowed." },
  LOYALTY_SPENDING_NOT_FOUND: { description: "Loyalty spending not found." },
  LOYALTY_SSE_ERROR: { description: "Error in SSE." },
  LOYALTY_STATUS_ERROR: { description: "Error in updating status." },
  MARKET_PLACE_VOUCHER_ALREADY_REQUESTED: { description: "Marketplace voucher already requested." },
  MARKET_PLACE_VOUCHER_EXCEED_QUANTITY: { description: "Marketplace voucher quantity exceeded." },
  MARKET_PLACE_VOUCHER_NOT_FOUND: { description: "Marketplace voucher not found." },
  MASTER_MERCHANT_CANNOT_SAME_MERCHANT: { description: "Master merchant cannot be your own." },
  MASTER_MERCHANT_NOT_SUBSCRIBE: { description: "Master merchant not subscribed to this product." },
  MASTER_MERCHANT_SUBSCRIPTION_EXPIRED: { description: "Master merchant subscription expired." },
  MASTER_MERCHANT_SUBSCRIPTION_NOT_ACTIVE: { description: "Master merchant subscription not active." },
  MAX_VALUE: { description: "Account update failed — value is too long." },
  MAX_VALUE_MEMBER_TIER: { description: "Reached maximum limit for member tier." },
  MAX_VALUE_ROLE: { description: "Reached maximum limit for creating a role." },
  MAYBANK_FAIL_TO_CANCELLED: { description: "Maybank failed to cancel." },
  MAYBANK_KEY_EXPIRED: { description: "Maybank key expired." },
  MAYBANK_KEY_NOT_FOUND: { description: "Maybank key not found." },
  MAYBANK_MALAYSIA_MERCHANT_ID_NOT_SET: { description: "Maybank Malaysia is not active.", solution: "Contact Revenue Monster to activate merchant for Maybank." },
  MAYBANK_MALAYSIA_NOT_ACTIVE: { description: "Maybank Malaysia is not active.", solution: "Contact Revenue Monster to activate merchant for Maybank." },
  MEMBER_NOT_FOUND: { description: "Member not found." },
  MEMBER_NOT_MERCHANT: { description: "Member does not belong to merchant." },
  MEMBER_PARENT_INVALID: { description: "Invalid member parent." },
  MEMBER_REGISTERED: { description: "Member already registered." },
  MEMBER_TIER_MAX: { description: "Reached max member tier." },
  MEMBER_TIER_NOT_FOUND: { description: "Member tier not found." },
  MENU_INVALID: { description: "Invalid menu." },
  MERCHANT_CHOP_STAMP_EXPIRED: { description: "Merchant chop stamp event has expired." },
  MERCHANT_CHOP_STAMP_NOT_FOUND: { description: "Merchant chop stamp event not found." },
  MERCHANT_CHOP_STAMP_NOT_STARTED: { description: "Merchant chop stamp event not started." },
  MERCHANT_GALLERY_NOT_FOUND: { description: "Merchant gallery not found." },
  MERCHANT_ID_INVALID: { description: "Invalid merchant ID." },
  MERCHANT_INACTIVE: { description: "Merchant account is inactive." },
  MERCHANT_KEY_INVALID: { description: "Invalid merchant key." },
  MERCHANT_MDR_NOT_SET: { description: "Merchant MDR not set.", solution: "Contact Revenue Monster to set." },
  MERCHANT_NOT_ACTIVE: { description: "Merchant not active." },
  MERCHANT_NOT_FOUND: { description: "Merchant not found." },
  MERCHANT_NOT_HAVE_MASTER_MERCHANT: { description: "Merchant does not have a master merchant." },
  MERCHANT_NOT_HAVE_PARTNER: { description: "Merchant does not have a partner." },
  MERCHANT_NOT_SAME: { description: "Merchant not same." },
  MERCHANT_NOT_SETUP: { description: "Merchant not set up." },
  MERCHANT_REQUESTED_JOIN: { description: "Merchant already requested to join as sub-merchant." },
  MERCHANT_REQUESTED_JOIN_NOT_FOUND: { description: "Merchant join request not found." },
  MERCHANT_SUSPENDED: { description: "Merchant suspended." },
  MERCHANT_VERIFIED: { description: "Merchant profile is verified." },
  MESSAGE_TYPE_NOT_FUND: { description: "Message type not found." },
  MESSENGER_ACCOUNT_EXISTS: { description: "Messenger account already exists." },
  MESSENGER_CODE_EXPIRED: { description: "Messenger code expired." },
  MESSENGER_INVALID_TOKEN: { description: "Invalid messenger token." },
  MESSENGER_MEMBER_DUPLICATE: { description: "Messenger member already registered." },
  MESSENGER_OWNER_ALLOW_CONNECT: { description: "Only messenger owner is allowed to connect." },
  MESSENGER_OWNER_INVALID: { description: "Invalid messenger owner." },
  MESSENGER_PAGE_DUPLICATE: { description: "Duplicate messenger page." },
  MESSENGER_PAGE_NOT_FOUND: { description: "Messenger page not found." },
  METHOD_NOT_ALLOWED: { description: "Method not allowed." },
  MINIMUM_AMOUNT_REQUIRED: { description: "Minimum amount should be 10 sen." },
  MIN_PTS_DUPLICATE: { description: "Min point exists in member tier." },
  MONEY_PACKET_EXPIRED: { description: "Money packet has expired." },
  MONEY_PACKET_NOT_FOUND: { description: "Money packet not found." },
  MONEY_PACKET_NOT_REDEEMED: { description: "Money packet has been redeemed." },
  NINE_GRID_MERCHANT_NOT_ALLOW_PAYMENT: { description: "Nine Grid merchant not allowed to make payment." },
  NO_ACCESS: { description: "This application is not allowed access." },
  NO_APP_ID: { description: "Missing app ID parameter." },
  NO_MERCHANT_ID: { description: "Missing merchant ID parameter." },
  NO_METHOD: { description: "Missing method parameter." },
  NOT_ALLOW_DELETE_APPROVED_JOIN_REQUEST: { description: "Delete and join requests not allowed." },
  NOT_ALLOW_LINK_PRODUCTION: { description: "Not allowed to link for production." },
  NOT_ALLOW_REFUND: { description: "Refund not allowed." },
  NOT_AUTH: { description: "Could not authenticate." },
  NOT_AUTHORIZE_USER_STORE: { description: "User store is not authorized." },
  NOT_MASTER_MERCHANT: { description: "Not a master merchant." },
  NOT_MASTER_MERCHANT_ACCOUNT: { description: "Not a master merchant account." },
  NOT_NINER_GRID_MERCHANT: { description: "Not a Nine Grid merchant." },
  NOT_PARTNER_ACCOUNT: { description: "Not a partner account." },
  NOT_PERMITTED: { description: "Not permitted to perform this action." },
  NOT_SUBSCRIBE: { description: "Merchant not subscribed to this product." },
  NOT_TERMNAL_TRANSACTION: { description: "Transaction not allowed due to different terminal." },
  NOT_USER_STORE: { description: "Not a user store." },
  OLD_PW_INVALID: { description: "Invalid old password." },
  ONLY_FREE_TIER_PLUGIN: { description: "Only free tier plugin allowed." },
  ONLY_OWNER_ALLOW_FOR_E_AGREEMENT: { description: "Only owner is allowed to view E-Agreement." },
  OPEN_FAIL: { description: "Failed to request open ID." },
  ORDER_CANCELLED: { description: "Order cancelled." },
  ORDER_CLOSED: { description: "Order error." },
  ORDER_ID_DUPLICATE: { description: "Order ID duplicate." },
  ORDER_NOT_EXIST: { description: "Order does not exist." },
  ORDER_NOT_PAID: { description: "Order not paid." },
  ORDER_PAID: { description: "Order already paid." },
  ORIGIN_INVALID: { description: "Invalid origin type." },
  OVERLOAD: { description: "Over capacity." },
  OWNER_NOT_ALLOWED_CREATE: { description: "Creating owner not allowed." },
  OWNER_NOT_ALLOWED_DELETE: { description: "Deleting owner is not allowed." },
  OWNER_NOT_ALLOWED_UPDATE: { description: "Updating owner is not allowed." },
  PAGE_NOT_FOUND: { description: "Sorry, that page does not exist." },
  PARTNER_MDR_NOT_SET: { description: "Partner MDR is not set.", solution: "Contact Revenue Monster to set the partner MDR." },
  PARTNER_NOT_FOUND: { description: "Partner not found." },
  PARTNER_NOT_SAME: { description: "Partner not same." },
  PASSWORD_INVALID: { description: "Email address or password is wrong." },
  PASSWORD_NOT_STRENGTH: { description: "Password is not strong enough." },
  PASSWORD_REQUIRED: { description: "Pending customer password." },
  PAYMENT_AMT_INVALID: { description: "Invalid amount format." },
  PAYMENT_CURRENCY_INVALID: { description: "Payment currency is invalid." },
  PAYMENT_DECIMAL_INVALID: { description: "Invalid decimal." },
  PAYMENT_EXCEED_AMOUNT_LIMIT_PER_TRANSACTION: { description: "Transaction amount is over the limit." },
  PAYMENT_EXCEED_AMOUNT_PER_DAY: { description: "Payment exceeds amount per day." },
  PAYMENT_EXCEED_AMOUNT_PER_MONTH: { description: "Payment exceeds amount for the month." },
  PAYMENT_EXCEED_NO_TRANSACTION_PER_DAY: { description: "Exceeded number of daily transactions." },
  PAYMENT_EXCEED_AMOUNT_LIMIT_PER_MONTH: { description: "Exceeded number of monthly transactions." },
  PAYMENT_FULLY_REFUNDED: { description: "Payment already fully refunded." },
  PAYMENT_LIMIT_NOT_SET: { description: "Payment limit not set.", solution: "Contact Revenue Monster to set the limit." },
  PAYMENT_PARAM_INVALID: { description: "Invalid payment parameters." },
  PAYMENT_REDIRECT: { description: "Merchant ID and redirect URL not found." },
  PAYMENT_REFUND_AMOUNT_EXCEED_PER_DAY: { description: "Refund amount has exceeded sales amount of the day." },
  PAYMENT_REFUNDING: { description: "Refund is still being processed." },
  PAYMENT_SCAN_INVALID: { description: "Invalid platform scan." },
  PAYMENT_SUBSCRIPTION_METHOD_ACTIVE: { description: "Payment method is active." },
  PAYMENT_TIMEOUT: { description: "Payment timeout." },
  PAYMENT_UNSUPPORTED_CURRENCY_TYPE: { description: "Unsupported currency type." },
  PHONE_DUPLICATE: { description: "Phone number already exists." },
  PIN_INVALID: { description: "Pin is invalid." },
  PLATFORM_NOT_FOUND: { description: "Platform not found." },
  PLUGIN_ALREADY_INSTALLED: { description: "Plugin already installed." },
  PLUGIN_NOT_ALLOW_TO_UPDATE_PRICING: { description: "Plugin not allowed to update pricing." },
  PLUGIN_NOT_FOUND: { description: "Plugin not found." },
  PLUGIN_NOT_INSTALLED: { description: "Plugin not installed." },
  PLUGIN_NOT_VERIFIED: { description: "Plugin not verified." },
  PLUGIN_SHOULD_GREATE_THAN_PREVIOUS_VERSION: { description: "Plugin version should be greater than previous version." },
  PRESTO_MALAYSIA_NOT_ACTIVE: { description: "Presto Malaysia is not active.", solution: "Contact Revenue Monster to activate merchant for Presto." },
  PRESTO_MDR_NOT_SET: { description: "Presto MDR not set.", solution: "Contact Revenue Monster to set." },
  PRESTO_MERCHANT_ID_NOT_SET: { description: "Presto merchant ID not set.", solution: "Contact Revenue Monster to set the merchant ID." },
  PRIVATE_KEY_READ_FILE: { description: "Cannot read private key." },
  PRODUCT_SUBSCRIPTION_ACTIVE: { description: "Product subscription is active." },
  QR_INVALID: { description: "Invalid QR code." },
  QR_REDEEMED: { description: "QR code redeemed." },
  QUICK_PAY_NOT_REGISTERED: { description: "User is not registered with Quick Pay." },
  RECONCILIATION_NOT_FOUND: { description: "Reconciliation record not found." },
  REDEMPTION_MERCHANT_INVALID: { description: "Invalid redemption rule merchant." },
  REDEMTION_PARENT_INVALID: { description: "Invalid redemption rule parent key." },
  REDEMPTION_RULE_KEY_FOUND: { description: "Invalid redemption rule key." },
  REDEMPTION_RULE_LIMIT_REACHED: { description: "Reached the voucher limit per member." },
  REDEMPTION_RULE_NOT_FOUND: { description: "Redemption rule not found." },
  REFUND_AMT_NOT_SAME_AS_TOTAL_AMOUNT: { description: "Refund amount not same as total amount." },
  REFUND_AMT_NOT_SAME_AS_TRANSACTION: { description: "Refund amount not same as transaction amount." },
  REFUND_PAYMENT_NOT_FOUND: { description: "Refund payment not found." },
  REFUND_PIN_INVALID: { description: "Wrong pin number." },
  REFUND_USER_NOT_FOUND: { description: "Refund user not found." },
  REPORT_NOT_FOUND: { description: "Report does not exist." },
  RESET_KEY_INVALID: { description: "Invalid password reset key." },
  RESET_LINK_EXPIRED: { description: "Password reset link expired." },
  RESOURCE_GONE: { description: "Resource no longer exists." },
  ROLE_KEY_INVALID: { description: "Invalid role key." },
  ROLE_NOT_FOUND: { description: "Role not found." },
  SCOPE_NOT_FOUND: { description: "Scope not found." },
  SHOULD_HAVE_INDEX_FILE: { description: "Should have index.html file." },
  SIGNATURE_INVALID: { description: "Invalid signature.", solution: "Check your signing logic — ensure the plaintext is constructed correctly with sorted body, method, nonceStr, requestUrl, signType, and timestamp." },
  SMS_FAIL: { description: "Failed to send SMS." },
  SPAM: { description: "Suspicious activity detected." },
  SPENDING_DUPLICATE: { description: "Spending loyalty already set." },
  SPENDING_NOT_FOUND: { description: "No spending loyalty found." },
  SSL_REQUIRED: { description: "SSL is required." },
  STORE_ID_INVALID: { description: "Invalid store ID." },
  STORE_INVALID_FORMAT: { description: "Store format invalid." },
  STORE_KEY_INVALID: { description: "Invalid store key." },
  STORE_MAXIMUM: { description: "Maximum store limit reached.", solution: "Maximum stores that can be created is 10." },
  STORE_NOT_FOUND: { description: "Store not found." },
  STORE_NOT_SET: { description: "Store not set." },
  SUB_MERCHANT_DOES_NOT_ALLOWED_LOYALTY: { description: "Sub-merchant not allowed to access loyalty." },
  SUBSCRIPTION_EXISTS: { description: "Merchant already subscribed to this product." },
  SUBSCRIPTION_EXPIRED: { description: "Merchant subscription expired." },
  SUBSCRIPTION_NOT_ACTIVE: { description: "You have not subscribed to this product." },
  SUBSCRIPTION_NOT_FOUND: { description: "Subscription not found." },
  SYSTEM_ERROR: { description: "System timed out.", solution: "If this persists, contact customer support." },
  TAC_INVALID: { description: "Invalid TAC code." },
  TAC_LIMIT: { description: "TAC code limit has been reached." },
  TAC_REQUIRED: { description: "User TAC code is required." },
  TAC_SENT: { description: "TAC code has been sent." },
  TEMPLATE_BODY_INVALID: { description: "Invalid template body." },
  TEMPLATE_KEY_INVALID: { description: "Invalid template key." },
  TEMPLATE_KEYWORD_DUPLICATE: { description: "Invalid template keyword — duplicate." },
  TEMPLATE_MESSAGE_DRAFT: { description: "Draft template message." },
  TEMPLATE_MESSAGE_DUPLICATE: { description: "Invalid template message — duplicate." },
  TEMPLATE_NOT_FOUND: { description: "Template not found." },
  TERMINAL_ALREADY_REGISTERED: { description: "Terminal already registered." },
  TERMINAL_INACTIVE: { description: "Terminal is not active." },
  TERMINAL_NO_PERMISSION: { description: "Terminal does not have permission to access." },
  TERMINAL_NOT_FOUND: { description: "Terminal not found." },
  TERMINAL_REFUND_TOKEN_INVALID: { description: "Terminal refund token invalid." },
  TERMINAL_SERIAL_ALREADY_EXIST: { description: "Terminal serial already exists." },
  TERMINAL_SERIAL_NOT_FOUND: { description: "Terminal serial not found." },
  TNG_MALAYSIA_NOT_ACTIVE: { description: "TNG Malaysia is not active.", solution: "Contact Revenue Monster to activate merchant for TNG." },
  TOKEN_EXPIRED: { description: "Invalid or expired token.", solution: "Re-run the Client Credentials endpoint to obtain a new access token." },
  TOKEN_INVALID: { description: "Unable to verify your credentials.", solution: "Ensure the access token is correctly set and was obtained from the Authorization server." },
  TOKEN_SUSPENDED: { description: "Access token suspended." },
  TRANSACTION_DUPLICATE: { description: "Duplicate order number.", solution: "Use a unique orderId for each transaction." },
  TRANSACTION_EXPIRED: { description: "Transaction has expired." },
  TRANSACTION_NOT_FOUND: { description: "No payment transaction found." },
  TRANSACTION_PAID: { description: "Transaction already paid." },
  TRANSACTION_QR_CODE_NOT_FOUND: { description: "Transaction QR code not found." },
  TRANSACTION_STATUS_FAILED: { description: "Payment transaction status failed." },
  TRANSACTION_STATUS_NOT_IN_PROCESS: { description: "Transaction status is not being processed." },
  TRANSACTIN_STATUS_NOT_SUCCESS: { description: "Transaction status not successful." },
  UNAUTHORIZED: { description: "Unauthorized." },
  UNIQUE_CODE_DUPLICATE: { description: "Duplicate unique code." },
  UNIQUE_CODE_EMPTY: { description: "Empty unique code." },
  UNIQUE_CODE_INVALID: { description: "Invalid unique code." },
  UNSUPPORTED_JSAPI_METHOD: { description: "Unsupported method for JSAPI." },
  UNSUPPORTED_JSAPI_REGION: { description: "Unsupported region for JSAPI." },
  UNSUPPORTED_METHOD_PAYMENT_REFUND: { description: "Unsupported payment refund method." },
  UNSUPPORTED_METHOD_REVERSE: { description: "Unsupported method for reverse." },
  USER_ALREADY_REGISTERED: { description: "User already registered." },
  USER_CANNOT_UPDATE_OWN_ACCOUNT: { description: "User cannot update own account." },
  USER_CREATE_FAIL: { description: "Unauthorized to create user." },
  USER_DELETE_FAIL: { description: "Unauthorized to delete user." },
  USER_DEVICE_NOT_FOUND: { description: "User device not found." },
  USER_DUPLICATE: { description: "User account already exists." },
  USER_KEY_INVALID: { description: "Invalid user key." },
  USER_NO_PERMISSION: { description: "User does not have permission to access." },
  USER_NOT_ACTIVE: { description: "User not active." },
  USER_NOT_CREATE_ACCOUNT: { description: "User cannot create account." },
  USER_NOT_FOUND: { description: "User not found." },
  USER_PIN_CODE_INVALID: { description: "Invalid user pin code." },
  USER_PROFILE_NOT_FOUND: { description: "User login profile not found." },
  USER_SUSPENDED: { description: "User has been suspended." },
  VALIDATION_ERROR: { description: "Validation error." },
  V_EMAIL_NOT_FOUND: { description: "User verification email not found." },
  VERIFICATION_CODE_ALREADY_REQUESTED: { description: "Verification code already requested." },
  VERIFICATION_CODE_INVALID: { description: "Verification code invalid." },
  VERIFICATION_CODE_REACH_DAILY_LIMIT: { description: "Verification code requests have reached daily limit." },
  VERIFICATION_TOKEN_INVALID: { description: "Invalid verification token." },
  VERIFICATION_TYPE_NOT_FOUND: { description: "Verification code type not found." },
  V_LINK_EXPIRED: { description: "Verification link has expired." },
  VOUCHER_BATCH_EXPIRED: { description: "Voucher batch expired." },
  VOUCHER_BATCH_KEY_INVALID: { description: "Voucher batch key is invalid." },
  VOUCHER_BATCH_NOT_ENOUGH_QUANTITY: { description: "Voucher batch does not have enough quantity." },
  VOUCHER_BATCH_NOT_FOUND: { description: "Voucher batch not found." },
  VOUCHER_COMBO_EXPIRED: { description: "Voucher combo expired." },
  VOUCHER_COMBO_NOT_ENOUGH_QUANTITY: { description: "Voucher combo does not have enough quantity." },
  VOUCHER_COMBO_NOT_FOUND: { description: "Voucher combo not found." },
  VOUCHER_INSUFFICIENT: { description: "Insufficient voucher batch." },
  VOUCHER_NOT_ALLOW_VOID: { description: "Voucher not allowed to void." },
  VOUCHER_NOT_FOUND: { description: "Voucher not found." },
  VOUCHER_NOT_MERCHANT: { description: "Voucher does not belong to merchant." },
  VOUCHER_NOT_MINIMUM_AMOUNT: { description: "Voucher does not meet minimum amount." },
  VOUCHER_NOT_REDEEMED: { description: "Voucher has not been redeemed." },
  VOUCHER_OWNER_INVALID: { description: "Voucher not owned." },
  VOUCHER_REDEEMED: { description: "Voucher redeemed." },
  VOUCHER_REDEEMED_INVALID: { description: "Voucher redeemed is invalid." },
  VOUCHER_REDEEM_MAX: { description: "Voucher has reached maximum redemption limit." },
  VOUCHER_SOLD_OUT: { description: "Voucher sold out." },
  WECHAT_ACCOUNT_DUPLICATE: { description: "WeChat account already exists." },
  WECHAT_PAGE_DUPLICATE: { description: "Duplicate WeChat page." },
  WECHAT_PAGE_INVALID: { description: "Invalid WeChat page." },
  WECHAT_PAGE_NOT_FOUND: { description: "WeChat page not found." },
  WECHATPAY_CHINA_MDR_NOT_SET: { description: "WeChat Pay China MDR not set.", solution: "Contact Revenue Monster to set." },
  WECHATPAY_CHINA_MERCHANT_ID_NOT_SET: { description: "WeChat Pay China merchant ID not set.", solution: "Contact Revenue Monster to set the merchant ID." },
  WECHATPAY_CHINA_NOT_ACTIVE: { description: "WeChat Pay China is not active.", solution: "Contact Revenue Monster to activate merchant for WeChat Pay." },
  WECHATPAY_CLIENT_DUPLICATE: { description: "WeChat Pay client duplicate." },
  WECHATPAY_CLIENT_NOT_FOUND: { description: "WeChat Pay client not found." },
  WECHATPAY_MALAYSIA_MDR_NOT_SET: { description: "WeChat Pay Malaysia MDR not set.", solution: "Contact Revenue Monster to set." },
  WECHATPAY_MALAYSIA_MERCHANT_ID_NOT_SET: { description: "WeChat Pay Malaysia merchant ID not set.", solution: "Contact Revenue Monster to set the merchant ID." },
  WECHATPAY_MALAYSIA_NOT_ACTIVE: { description: "WeChat Pay Malaysia is not active.", solution: "Contact Revenue Monster to activate merchant for WeChat Pay." },
  WECHAT_PHONE_INVALID: { description: "Invalid WeChat phone number." },
  WECHAT_TEMPLATE_MESSAGE_FAILED: { description: "WeChat template message failed." },
  TOO_MANY_REQUEST_PER_SECOND: { description: "Reached maximum request limit per second.", solution: "Back off and retry after a short delay." },
  TERMINAL_BUSY: { description: "Existing request in process." },
  TERMINAL_RESTARTED: { description: "Activity restarted." },
  PAYMENT_IN_PROCESS: { description: "Existing payment in process." },
  ORDER_CANCELLED_ACTIVITY_TIMEOUT: { description: "Order canceled due to payment activity timeout." },
  PAYMENT_FAIL: { description: "Invalid payment type request." },
  NO_CARD_PAY: { description: "Bank card module not enabled." },
  APPLICATION_CONTEXT_ERR: { description: "Requesting from an activity that is not a BaseActivity is not supported." },
  SETTLEMENT_FAILURE: { description: "Settlement failure." },
  REFUND_FAILURE: { description: "Refund failure." },
  UNSUPPORTED_REFUND: { description: "Unsupported refund." },
  NO_TRANSACTION_DETAIL: { description: "No transaction details returned." },
  CANCELLATION_ERROR: { description: "No payment is ongoing." },
  CANCELLATION_UNSUPPORTED: { description: "Cancellation is not supported for card payment on terminal." },
};

/**
 * Look up an error code — case-insensitive, handles both
 * SCREAMING_SNAKE_CASE and PascalCase formats.
 */
export function lookupError(code: string): ErrorEntry | null {
  if (!code) return null;
  // Direct match first
  if (ERROR_CODES[code]) return ERROR_CODES[code];
  // Case-insensitive fallback
  const upper = code.toUpperCase();
  const found = Object.keys(ERROR_CODES).find(
    (k) => k.toUpperCase() === upper
  );
  return found ? ERROR_CODES[found] : null;
}

/**
 * Extract all error codes present anywhere in an API response object.
 * Walks the full response tree so nested error structures are covered.
 */
export function extractErrorCodes(obj: any, found: string[] = []): string[] {
  if (!obj || typeof obj !== "object") return found;
  for (const [key, val] of Object.entries(obj)) {
    if (
      (key === "code" || key === "errorCode" || key === "error_code") &&
      typeof val === "string"
    ) {
      found.push(val);
    } else if (key === "error" && typeof val === "object" && val !== null) {
      extractErrorCodes(val, found);
    } else if (Array.isArray(val)) {
      val.forEach((item) => extractErrorCodes(item, found));
    } else if (typeof val === "object") {
      extractErrorCodes(val, found);
    }
  }
  return [...new Set(found)];
}